package org.amm.euler.p100;

/**
 *  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 *  By starting with 1 and 2, the first 10 terms will be:
 *
 *  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 *  find the sum of the even-valued terms.
 *
 */
public class Problem_02 {

	public static Long solution_1(Long n) {
		long sum = 0;
		long temp = 0;
		for (long prev = 1, current = 2; current < n;) {
			if (current % 2 == 0) {
				sum += current;
			}
			temp = prev;
			prev = current;
			current += temp;
		}
		return sum;
	}
	
}
